### ISSUE TITLE
Works with RN 0.14+

### ISSUE THREAD

**Issue by agillesp** [wmcmahan/React-Native-LocalSearch#1]
The moment a view runs the following

```
var RNLocalSearch = require('react-native-localsearch');
```

my app crashes.  I noticed that `package.json` references a fairly old version of RN.  Is it possible you could update things?

Thanks!

**Comment by wmcmahan** [comment]
Thanks, I've bumped the version up.

**Comment by agillesp** [comment]
@wmcmahan Thanks for doing this! Turns out I had to reference the .h and .m file directly in the root of my project. Adding the .xcodeproj to my RN Libraries folder didn't work. This is a great little utility anyway, thanks for your help!

<img width="308" alt="client_xcodeproj" src="https://cloud.githubusercontent.com/assets/1098950/11355211/1725b244-9208-11e5-86ec-a898532b4d5c.png">

**Comment by wmcmahan** [comment]
@agillesp Glad its working. You can also add `libRNLocalSearch.a` into the projects 'Build Phases' under 'Link Binary With Libraries'. This should alleviate any need to move files from the 'Libraries' folder. The RN docs have a [Linking Libraries](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content) guide that does a good job explaining.

**Comment by agillesp** [comment]
That did the trick! Thanks for taking the time out to help a fellow dev.
